site_name: 3DRadSpace Documentation

repo_url: https://github.com/3DRadSpace/3D_Rad_Space 
repo_name: 3DRadSpace\3D_Rad_Space 

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

theme:
  name: material
  logo: assets/Logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny


        name: Switch to dark mode
    - scheme: slate 


      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

